language: python
python:
  - "pypy3"
  - "pypy"
  - "3.8"
  - "3.7"
  - "3.6"
  - "3.5"
  - "2.7"
  - "3.9-dev"

cache: pip

env:
  global:
    - PYTEST_COMMAND="coverage run -m pytest"
  matrix:
    - TOXENV=optional
    - TOXENV=base
    - TOXENV=six19-optional

install:
  - pip install tox codecov

script:
  - tox

after_script:
  - python debug-info.py

after_success:
- codecov

deploy:
  - provider: pypi
    server: https://test.pypi.org/legacy/
    on:
      tags: false
      repo: html5lib/html5lib-python
      branch: master
      condition: "$TOXENV = py36-base"
    user: __token__
    password:
      secure: "TODO"
    distributions: sdist --format=gztar bdist_wheel
    skip_existing: true
  - provider: pypi
    on:
      tags: true
      repo: html5lib/html5lib-python
      branch: master
      condition: "$TOXENV = py36-base"
    user: __token__
    password:
      secure: "TODO"
    distributions: sdist --format=gztar bdist_wheel
    skip_existing: true
